# Generated by Django 2.1.5 on 2019-02-07 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20190207_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Category', verbose_name='Бренд'),
        ),
        migrations.AddField(
            model_name='product',
            name='model_phone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.ModelPhone', verbose_name='Модель'),
        ),
    ]
