# Generated by Django 2.1.5 on 2019-02-07 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20190207_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='model_phone',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
