# Generated by Django 2.1.5 on 2019-02-07 15:05

import autoslug.fields
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20190207_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Цена')),
                ('specifications', ckeditor.fields.RichTextField(blank=True, verbose_name='Характеристики')),
                ('properties', ckeditor.fields.RichTextField(blank=True, verbose_name='Свойства')),
                ('image', models.ImageField(upload_to='products')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=True, populate_from='title', unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Category', verbose_name='Бренд')),
                ('model_phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.ModelPhone', verbose_name='Модель')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
