# Generated by Django 2.1.5 on 2019-02-11 19:43

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20190211_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=True, populate_from='title', unique=True),
        ),
    ]
