# Generated by Django 2.1.5 on 2019-02-28 11:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_auto_20190228_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Комент'),
        ),
    ]
