# Generated by Django 2.1.5 on 2019-03-04 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_propertyimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='in_sale',
            field=models.BooleanField(default=False, verbose_name='Учавствует в распродаже?'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='Новый товар?'),
        ),
    ]
