# Generated by Django 2.1.5 on 2019-03-04 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_product_sale_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address',
            new_name='city',
        ),
        migrations.AddField(
            model_name='order',
            name='new_poch',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, verbose_name='Цена с Скидкой'),
        ),
    ]
