# Generated by Django 2.1.5 on 2019-03-11 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_auto_20190304_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_image', models.ImageField(upload_to='products')),
                ('sub_head_text', models.CharField(blank=True, max_length=200, verbose_name='Подзаголовок')),
                ('head_text', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('url_button', models.URLField(verbose_name='Ссылка в кнопку')),
                ('sale_img', models.ImageField(upload_to='products')),
                ('percent', models.CharField(max_length=200, verbose_name='Процент скидки')),
                ('text', models.CharField(max_length=200, verbose_name='Заголовок распродажи')),
                ('btn_sale', models.URLField(verbose_name='Ссылка в кнопку распродажи')),
            ],
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказы', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='new_poch',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
