# Generated by Django 2.1.5 on 2019-03-11 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_auto_20190311_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpage',
            name='text_btn',
            field=models.CharField(blank=True, max_length=200, verbose_name='Текст кнопки'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='btn_sale',
            field=models.URLField(blank=True, verbose_name='Ссылка в кнопку распродажи'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='head_text',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='percent',
            field=models.CharField(blank=True, max_length=200, verbose_name='Процент скидки'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='text',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок распродажи'),
        ),
    ]
