# Generated by Django 2.1.5 on 2019-03-11 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_auto_20190311_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpage',
            name='text_btn_sale',
            field=models.CharField(default='Текст кнопки скидки', max_length=200, verbose_name='Текст кнопки скидки'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='text_btn',
            field=models.CharField(max_length=200, verbose_name='Текст кнопки'),
        ),
    ]
