# Generated by Django 2.1.5 on 2019-03-11 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_auto_20190311_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpage',
            name='is_active_sale',
            field=models.BooleanField(default=False, verbose_name='Есть ли распродажа?'),
        ),
    ]
