# Generated by Django 2.1.5 on 2019-03-12 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_auto_20190312_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyorder',
            name='pr',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='shop.Product'),
        ),
        migrations.AlterField(
            model_name='propertyorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Order'),
        ),
    ]
