# Generated by Django 2.1.5 on 2019-03-12 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0035_auto_20190312_2322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyorder',
            name='pr',
        ),
        migrations.AddField(
            model_name='propertyorder',
            name='object_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
