# Generated by Django 2.1.5 on 2019-03-12 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('shop', '0036_auto_20190312_2327'),
    ]

    # operations = [
    #     migrations.AddField(
    #         model_name='propertyorder',
    #         name='content_type',
    #         field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
    #     ),
    #     migrations.AlterField(
    #         model_name='propertyorder',
    #         name='object_id',
    #         field=models.PositiveIntegerField(),
    #     ),
    # ]
