# Generated by Django 2.1.5 on 2019-03-12 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0038_auto_20190312_2336'),
    ]

    # operations = [
    #     migrations.AlterField(
    #         model_name='propertyorder',
    #         name='content_type',
    #         field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
    #     ),
    # ]
