# Generated by Django 2.1.5 on 2019-03-12 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0039_auto_20190312_2336'),
    ]

    # operations = [
    #     migrations.RemoveField(
    #         model_name='propertyorder',
    #         name='content_type',
    #     ),
    #     migrations.RemoveField(
    #         model_name='propertyorder',
    #         name='object_id',
    #     ),
    # ]
