# Generated by Django 2.1.5 on 2019-03-12 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('shop', '0041_remove_propertyorder_object_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyorder',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='propertyorder',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
