# Generated by Django 2.1.5 on 2019-04-04 20:16

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0044_auto_20190329_1004'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_info', ckeditor.fields.RichTextField(verbose_name='Текст о доставке')),
            ],
        ),
    ]
